# Create a Vector

In [1]:
#Use numpy to create a one-dimensional array

#load lirary
import numpy as np

In [2]:
#Create a vector as row
vector_row = np.array([1,2,3])
print(vector_row)

[1 2 3]


In [3]:
#Create a vector as column
vector_column = np.array([[1],
                          [2],
                          [3]])
print(vector_column)

[[1]
 [2]
 [3]]


# Creating a Matrix

In [4]:
#Use numPy to create a two-dimensional array: 

#load library
import numpy as np

#Create a matrix
matrix = np.array([[1,2],
                   [1,2],
                   [1,2]])
print(matrix)


[[1 2]
 [1 2]
 [1 2]]


In [5]:
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])
print(matrix_object)

[[1 2]
 [1 2]
 [1 2]]


# Create a Sparse matrix

Given data with very few nonzero values, you want to efficiently represent it.

In [6]:
#load libraries
import numpy as np
from scipy import sparse

#create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

#create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

print(matrix)
print(matrix_sparse)

[[0 0]
 [0 1]
 [3 0]]
  (1, 1)	1
  (2, 0)	3


In [9]:
#create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

#create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

#view original sparse matrix
print(matrix_sparse)

#view larger sparse matrix
print(matrix_large_sparse)


  (1, 1)	1
  (2, 0)	3



# Selecting Elements

You need to select one or more elements in a vector or matrix.


NumPy’s arrays make that easy:
  

In [18]:
#load library
import numpy as np

#create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

#create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

#select third element of vector
vector[2]

#select second row, second column
matrix[1,1]

print('vector is:',vector)

print('matrix is:',matrix)

print('vector of index 2 is :',vector[2])

print('matrix index 1:1 is:',matrix[1,1])

('vector is:', array([1, 2, 3, 4, 5, 6]))
('matrix is:', array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]))
('vector of index 2 is :', 3)
('matrix index 1:1 is:', 5)


In [20]:
#select all elements of a vector 
vector[:]



array([1, 2, 3, 4, 5, 6])

In [21]:
#select everything up to and including the third element
vector[:3]



array([1, 2, 3])

In [22]:
#select everything after the third element 
vector[3:]



array([4, 5, 6])

In [23]:
#select the last element
vector[-1]



6

In [24]:
#select the first two rows and alla columns of a matrix
matrix[:2,:]



array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
# Select all rows and the second column
matrix[:,1:2]


array([[2],
       [5],
       [8]])

# Describing a Matrix

You want to describe the shape, size, and dimensions of the matrix.

use shape , size, and N-dimension

In [26]:
#load library
import numpy as np

#create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
#view number of rows and columns
matrix.shape

(3, 4)

In [27]:
#view the size of elements (rows * columns)
matrix.size

12

In [28]:
#view number of dimensions
matrix.ndim

2

# Applying Operations to Elements

Use numpy's vectorize

In [33]:
#load library
import numpy as np

#create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
#create function that adds 100 to something
add_100 = lambda i: i +100

# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

# Apply function to all elements in matrix
vectorized_add_100(matrix)


array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [34]:
#Add 100 to all elements
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

# Finding the Maximum and Minimum Values

You need to find the maximum or minimum value in an array.

Use NumPy’s max and min :

In [35]:
#load library
import numpy as np

#create matrix 
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

#return max element
np.max(matrix)

9

In [36]:
#return min element
np.min(matrix)

1

In [37]:
#Find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [39]:
#find minimum element in each row
np.max(matrix, axis = 1)

array([3, 6, 9])

# Calculating the Average, Variance, and Standard


You want to calculate some descriptive statistics about an array.

Use NumPy’s mean , var , and std :

In [40]:
#load library 
import numpy as np

#create matrix
matrix =np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
#return mean
np.mean(matrix)

5.0

In [41]:
#return variance
np.var(matrix)

6.666666666666667

In [42]:
#return standard deviation
np.std(matrix)

2.581988897471611

In [43]:
#find the mean value in each column
np.mean(matrix, axis = 0)

array([4., 5., 6.])

# Reshaping Arrays

In [46]:
#load librar
import numpy as np

#create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

#Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [47]:
matrix.size


12

In [48]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [49]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Transposing a Vector or Matrix

You need to transpose a vector or matrix.

Use the T method:

In [50]:
#load library
import numpy as np

#create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [52]:
#Transpose Vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [53]:
#Transpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Flattening a Matrix

You need to transform a matrix into a one-dimensional array.

Use flatten:

In [55]:
#load library
import numpy as np

#create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
#Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Finding the Rank of a Matrix

You need to know the rank of a matrix

Use numpy linear algebra method of a matrix.

In [57]:
#load library 
import numpy as np

#Create matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

#Return matrix rank
np.linalg.matrix_rank(matrix)

2

# Calculating the Determinant

Use NumPy’s linear algebra method det :

In [58]:
#load library
import numpy as np

#create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

#Return determinant of matrix
np.linalg.det(matrix)

0.0

# Getting the Diagonal of a Matrix

You need to get the diagonal elements of a matrix.

Use diagonal:

In [59]:
#load library
import numpy as np

#create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

#Return diagonal elements
matrix.diagonal()

array([1, 5, 9])

In [60]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [61]:
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([4, 8])

# Calculating the Trace of a Matrix

You need to calculate the trace of a matrix.

In [62]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return trace
matrix.trace()

14

In [63]:
# Return diagonal and sum elements
sum(matrix.diagonal())

14

# Finding Eigenvalues and Eigenvectors

You need to find the eigenvalues and eigenvectors of a square matrix

Use NumPy’s linalg.eig :

In [64]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# View eigenvalues
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [65]:
# View eigenvectors
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

# Calculating Dot Products

You need to calculate the dot product of two vectors.

Use NumPy’s dot :

In [66]:
# Load library
import numpy as np

# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# Calculate dot product
np.dot(vector_a, vector_b)

32

# Adding and Subtracting Matrices

You want to add or subtract two matrices.

Use NumPy’s add and subtract :

In [69]:
# Load library
import numpy as np

# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])
# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])
# Add two matrices
np.add(matrix_a, matrix_b)



array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [70]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [71]:
# Add two matrices
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

# Multiplying Matrices

You want to multiply two matrices.

Use numpy's dot

In [72]:
# Load library
import numpy as np

# Create matrix
matrix_a = np.array([[1, 1],
                     [1, 2]])
# Create matrix
matrix_b = np.array([[1, 3],
                    [1, 2]])

# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [73]:
# Multiply two matrices element-wise
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

# Inverting a Matrix

You want to calculate the inverse of a square matrix.

Use NumPy’s linear algebra inv method:

In [74]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 4],
                   [2, 5]])
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

# Generating Random Values

You want to generate pseudorandom values.

Use NumPy’s random :

In [75]:
# Load library
import numpy as np

# Set seed
np.random.seed(0)

# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [76]:
# Generate three random integers between 1 and 10
np.random.randint(0, 11, 3)

array([3, 7, 9])

In [77]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [78]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [79]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])